version: '3.0'
services:
  frontend:
    image: ghcr.io/music-bot-for-jitsi/jimmi/frontend:latest
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      # HTTP
      - "traefik.http.routers.frontend.rule=Host(`localhost`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      # HTTPS
      - "traefik.http.routers.frontend-tls.rule=Host(`localhost`)"
      - "traefik.http.routers.frontend-tls.entrypoints=websecure"
      - "traefik.http.routers.frontend-tls.tls=true"

  backend:
    image: ghcr.io/music-bot-for-jitsi/jimmi/backend:latest
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      # HTTP
      - "traefik.http.routers.backend.rule=Host(`localhost`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=web"
      # HTTPS
      - "traefik.http.routers.backend-tls.rule=Host(`localhost`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend-tls.entrypoints=websecure"
      - "traefik.http.routers.backend-tls.tls=true"

  reverse-proxy:
    image: traefik:v2.5
    restart: unless-stopped
    command:
      - --providers.docker
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
      - "--providers.docker.exposedbydefault=false"
      # uncomment line to enable web ui
      # - --api.insecure=true
    ports:
      - "80:80"
      - "443:443"
      # uncomment line to access web ui (enabled by --api.insecure=true)
      # - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro