blank_issues_enabled: false
contact_links:
  - name: ❓ Community-driven support
    url: https://github.com/p-fruck/Jimmi/discussions
    about: Please use the community discussions for questions or assistance
