version: "3"
services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: bullseye
    volumes:
      - ..:/workspace:cached
    environment:
      - BROWSER_WS_ENDPOINT=ws://browserlessservice:3000
    command: sleep infinity
    links:
      - browserlessservice

  browserlessservice:
    image: browserless/chrome:1-chrome-stable
    restart: unless-stopped
    environment:
      - DEFAULT_LAUNCH_ARGS=["--use-fake-ui-for-media-stream","--use-fake-device-for-media-stream","--disable-web-security","--disable-features=IsolateOrigins,site-per-process"]
      - CONNECTION_TIMEOUT=-1
    links:
      - staticcontent
