name: CD - Build Binaries

on:
  release:
    types:
    - published
  workflow_dispatch:


jobs:
  build_all_portable:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      
      - name: Install snel
        run: deno run --allow-run --allow-read https://deno.land/x/snel/install.ts

      - name: Build all portables and thereby all binaries
        run: make all_portable

      - name: Copy files
        run: cp backend/dist/*.{tar.gz,zip} .

      - uses: actions/upload-artifact@v3
        with:
          path: |
            *.tar.gz
            *.zip
