# https://deno.land/manual@v1.19.2/continuous_integration

name: CI - Backend

on:
  pull_request:
    paths:
      - 'backend/**'
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: backend

jobs:
  check_formatting:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - name: Check backend formatting
        run: deno task fmt:check

  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - name: Lint the backend
        run: deno task lint

  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - name: Test the backend
        run: deno task test
