name: Codecov
# https://github.com/marketplace/actions/codecov
# https://app.codecov.io/gh/Music-Bot-for-Jitsi/Jimmi

on:
  push:
    branches:
      - main
      - automation/26-Setup-Codecov
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  analysis:
    name: Codecov Analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Setup deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: vx.x.x

    - name: Create coverage files
      run: deno test --unstable --coverage=coverage # create coverage files

    - name: Create coverage report
      run: deno --unstable coverage ./coverage --lcov > coverage.lcov # create coverage report

    - name: Collect coverage
      uses: codecov/codecov-action@v2
      with:
        files: ./coverage.lcov
        flags: unittests # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)
