# https://deno.land/manual@v1.19.2/continuous_integration

name: CI - Linting - Backend

on:
  pull_request:
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  lint-backend:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: Check backend formatting
        run: deno fmt --config deno.json --check

      - name: Lint the backend
        run: deno lint --config deno.json

      - name: Test the backend
        run: deno test --config deno.json --import-map=../import_map.json
