# https://deno.land/manual@v1.19.2/continuous_integration

name: CI - Linting - Frontend

on:
  pull_request:
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Check frontend formatting
        run: deno fmt --config deno.json --check

      - name: Lint the frontend
        run: deno lint --config deno.json

      - name: Test the frontend
        run: deno test --config deno.json --import-map=../import_map.json
