# https://deno.land/manual@v1.19.2/continuous_integration

name: CI - Linting - Backend

on:
  push:
    branches:
      - 'automation/22-Setup-CI'
  pull_request:
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Format the backend
        run: cd backend/ && deno fmt --config deno.json

      - name: Lint the backend
        run: cd backend/ && deno lint --config deno.json

      - name: Test the backend
        run: cd backend/ && deno test --config deno.json --import-map=../import_map.json
