name: Automation - Update API Client

on:
  push:
    branches:
      - main
      - feature/42-Setup-automatic-API-Client-Generation
  #path:
  #  - backend/src/**.ts

jobs:
  update-api-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          # Remove ref later!!!
          ref: feature/42-Setup-automatic-API-Client-Generation
          submodules: 'true'
          ssh-key: ${{ secrets.JIMMI_API_CLIENT_REPO_DEPLOY_KEY }}

      - name: Setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: Install dependencies
        run: |
          deno install -A --unstable \
          --import-map=https://deno.land/x/trex/import_map.json \
          -n trex --no-check https://deno.land/x/trex/cli.ts
          export PATH=$PATH:/home/runner/.deno/bin/trex

      - name: Start backend
        working-directory: backend
        # Add & to background!
        run: |
          deno run --no-check --allow-read --allow-net --config deno.json src/app.ts &
          sleep 1
          ps | grep " $! "

      - name: Delete old client files
        working-directory: frontend/lib/jimmi-api-client
        run: |
          git checkout main
          rm -rf src
          mkdir src
          sleep 3

      - name: Generate api client
        working-directory: frontend/lib/jimmi-api-client
        run: |
          docker run --rm \
          --add-host host.docker.internal:host-gateway \
          -v "$(pwd)":/local \
          openapitools/openapi-generator-cli generate \
          -i http://host.docker.internal:8000/swagger.json \
          -c /local/config.yml \
          -g typescript \
          -o /local/src/

      - name: Commit and push changes in submodule
        working-directory: frontend/lib/jimmi-api-client
        run: |
          mv src/index.ts src/mod.ts
          if ! git diff --quiet
          then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add -A
            if [ $? -ne 0 ]; then echo hi; fi
            git commit -m "Update api client" -a
            git push
          fi

      - name: Commit changes in main repo
        run: |
          if ! git diff --quiet
          then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add -A
            git commit -m "Update api client submodule" -a
          fi

      - name: Push changes in a new branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          #branch: main
          branch: automation/api-client-update
