name: Automation - Update API Client

on:
  push:
    branches:
      - main
      - feature/42-Setup-automatic-API-Client-Generation
  #path:
  #  - backend/src/**.ts

jobs:
  update-api-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          # Remove ref later!!!
          ref: feature/42-Setup-automatic-API-Client-Generation
          submodules: 'true'

      - name: Setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: Install dependencies
        run: |
          deno install -A --unstable \
          --import-map=https://deno.land/x/trex/import_map.json \
          -n trex --no-check https://deno.land/x/trex/cli.ts
          export PATH=$PATH:/home/runner/.deno/bin/trex

      - name: Start backend
        # Add & to background!
        run: |
          cd backend
          trex --version
          deno run --no-check --allow-read --allow-net --config deno.json --watch src/app.ts &
          # trex run start &

      - name: Delete old client
        run: |
          cd frontend/lib/jimmi-api-client
          git checkout main
          rm -rf src
          mkdir src
          sleep 5

      - name: Generate api client
        run: |
          pwd
          cd frontend/lib/jimmi-api-client
          docker run --rm \
          --add-host host.docker.internal:host-gateway \
          -v "$(pwd)":/local \
          openapitools/openapi-generator-cli generate \
          -i http://host.docker.internal:8000/swagger.json \
          -c /local/config.yml \
          -g typescript \
          -o /local/src/

      - name: Setup SSH deploy key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.JIMMI_API_CLIENT_REPO_DEPLOY_KEY }}

      - name: Commit changes in submodule
        run: |
          pwd
          git config submodule.jimmi-api-client.url git@github.com:Music-Bot-for-Jitsi/jimmi-api-client.git
          cd frontend/lib/jimmi-api-client
          git config remote.origin.url git@github.com:Music-Bot-for-Jitsi/jimmi-api-client.git
          git status
          git remote -v
          ssh -T git@github.com || true
          mv src/index.ts src/mod.ts
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Update api client" -a
          git push
          cd ../../../

      - name: Commit changes in main repo
        run: |
          pwd
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Update api client submodule" -a

      - name: Push changes in main repo
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          #branch: main
          branch: feature/42-Setup-automatic-API-Client-Generation
